const NEW_TASK = "NEW_TASK";
const DELETE_TASK = "DELETE_TASK";
const COMPLETE_TASK = "COMPLETE_TASK";
const UNCOMPLETE_TASK = "UNCOMPLETE_TASK";
const SUBMIT_FORM = "SUBMIT_FORM";
const RESET_FORM = "RESET_FORM";

module.exports = {
    NEW_TASK,
    DELETE_TASK,
    COMPLETE_TASK,
    UNCOMPLETE_TASK,
    SUBMIT_FORM,
    RESET_FORM
};