const NEW_TASK = "NEW_TASK";
const DELETE_TASK = "DELETE_TASK";
const COMPLETE_TASK = "COMPLETE_TASK";
const SHOW_VIEW = "SHOW_VIEW";
const SUBMIT_FORM = "SUBMIT_FORM";
const RESET_FORM = "RESET_FORM";

module.exports = {
    NEW_TASK,
    DELETE_TASK,
    COMPLETE_TASK,
    SHOW_VIEW,
    SUBMIT_FORM,
    RESET_FORM
};